### ISSUE TITLE
Large Dataset 100,000 groups or about 1,000,000 rows

### ISSUE THREAD

**Issue by csaiedu** [timothyb0912/pylogit#22] opened 2018-04-10 18:30 UTC
Hi 
Are there any fix implemented to deal with the memory errors when dealing with large datasets?
Thanks

**Comment by timothyb0912** [comment] 2018-04-11 00:07
Not yet. I'd like to implement an option to use stochastic gradient descent or some mini-batch method to deal with large datasets. I haven't made time to do so, and pull requests would be great here.

**Comment by timothyb0912** [comment] 2018-04-18 17:40
Closing as essentially a duplicate of [Issue #9](https://github.com/timothyb0912/pylogit/issues/9)

**Closed by timothyb0912** 2018-04-18 17:40 UTC
Labels: enhancement, help wanted
